//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18010
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OneBusAway.DataAccess.Test {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OneBusAway.DataAccess.Test.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;response&gt;
        ///  &lt;version&gt;1&lt;/version&gt;
        ///  &lt;code&gt;200&lt;/code&gt;
        ///  &lt;currentTime&gt;1351709286607&lt;/currentTime&gt;
        ///  &lt;text&gt;OK&lt;/text&gt;
        ///  &lt;data class=&quot;stop&quot;&gt;
        ///    &lt;id&gt;1_75403&lt;/id&gt;
        ///    &lt;lat&gt;47.654366&lt;/lat&gt;
        ///    &lt;lon&gt;-122.305214&lt;/lon&gt;
        ///    &lt;direction&gt;S&lt;/direction&gt;
        ///    &lt;name&gt;STEVENS WAY &amp;amp; BENTON LN&lt;/name&gt;
        ///    &lt;code&gt;75403&lt;/code&gt;
        ///    &lt;locationType&gt;0&lt;/locationType&gt;
        ///    &lt;routes&gt;
        ///      &lt;route&gt;
        ///        &lt;id&gt;1_25&lt;/id&gt;
        ///        &lt;shortName&gt;25&lt;/shortName&gt;
        ///        &lt;description&gt;Laurelhurst-Lakeview&lt;/description&gt;
        ///        &lt;type&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string getRoutesForStopXml {
            get {
                return ResourceManager.GetString("getRoutesForStopXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;response&gt;
        ///  &lt;version&gt;1&lt;/version&gt;
        ///  &lt;code&gt;200&lt;/code&gt;
        ///  &lt;currentTime&gt;1351629850901&lt;/currentTime&gt;
        ///  &lt;text&gt;OK&lt;/text&gt;
        ///  &lt;data class=&quot;stop&quot;&gt;
        ///    &lt;id&gt;1_75403&lt;/id&gt;
        ///    &lt;lat&gt;47.654366&lt;/lat&gt;
        ///    &lt;lon&gt;-122.305214&lt;/lon&gt;
        ///    &lt;direction&gt;S&lt;/direction&gt;
        ///    &lt;name&gt;STEVENS WAY &amp;amp; BENTON LN&lt;/name&gt;
        ///    &lt;code&gt;75403&lt;/code&gt;
        ///    &lt;locationType&gt;0&lt;/locationType&gt;
        ///    &lt;routes&gt;
        ///      &lt;route&gt;
        ///        &lt;id&gt;1_25&lt;/id&gt;
        ///        &lt;shortName&gt;25&lt;/shortName&gt;
        ///        &lt;description&gt;Laurelhurst-Lakeview&lt;/description&gt;
        ///        &lt;type&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string getRoutesXml {
            get {
                return ResourceManager.GetString("getRoutesXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;response&gt;
        ///  &lt;version&gt;1&lt;/version&gt;
        ///  &lt;code&gt;200&lt;/code&gt;
        ///  &lt;currentTime&gt;1351713956781&lt;/currentTime&gt;
        ///  &lt;text&gt;OK&lt;/text&gt;
        ///  &lt;data class=&quot;org.onebusaway.transit_data.model.StopsForRouteBean&quot;&gt;
        ///    &lt;route&gt;
        ///      &lt;id&gt;1_44&lt;/id&gt;
        ///      &lt;shortName&gt;44&lt;/shortName&gt;
        ///      &lt;description&gt;ballard/montlake&lt;/description&gt;
        ///      &lt;type&gt;3&lt;/type&gt;
        ///      &lt;url&gt;http://metro.kingcounty.gov/tops/bus/schedules/s044_0_.html&lt;/url&gt;
        ///      &lt;agency&gt;
        ///        &lt;id&gt;1&lt;/id&gt;
        ///        &lt;name&gt;Metro Transit&lt;/name&gt;
        ///        &lt;url&gt;http://metro.kingcou [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string getStopsForRouteXml {
            get {
                return ResourceManager.GetString("getStopsForRouteXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;response&gt;
        ///              &lt;version&gt;1&lt;/version&gt;
        ///              &lt;code&gt;200&lt;/code&gt;
        ///              &lt;currentTime&gt;1348786676170&lt;/currentTime&gt;
        ///              &lt;text&gt;OK&lt;/text&gt;
        ///              &lt;data class=&quot;org.onebusaway.transit_data.model.StopsBean&quot;&gt;
        ///                &lt;stops&gt;
        ///                  &lt;stop&gt;
        ///                    &lt;id&gt;1_10914&lt;/id&gt;
        ///                    &lt;lat&gt;47.656426&lt;/lat&gt;
        ///                    &lt;lon&gt;-122.312164&lt;/lon&gt;
        ///                    &lt;direction&gt;S&lt;/direction&gt;
        ///                    &lt;name&gt;15TH AVE NE &amp;amp; NE CAM [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string getStopsXml {
            get {
                return ResourceManager.GetString("getStopsXml", resourceCulture);
            }
        }
    }
}
